Aprendizado Supervisionado: Classificação Em tarefas preditivas, algoritmos de AM são aplicados a conjuntos de dados de treinamento rotulados para induzir um modelo preditivo capaz de predizer, para um novo objeto representado pelos valores de seus atributos preditivos, o valor de seu atributo alvo. Modelos preditivos podem ser utilizados, por exemplo, para, a partir de seus sintomas, predizer o estado de saúde de um paciente. Nessas tarefas, em geral são utilizados algoritmos de AM que seguem o paradigma de aprendizado supervisionado (FACELLI et al. 2021, pág. 3)

In [ ]:
import pandas as pd
import numpy as np
import itertools

Utilizado a base de dados Diabetes Prediction Dataset: https://www.kaggle.com/datasets/iammustafatz/diabetes-prediction-dataset como base para criar uma dataset prorpia usando o seguinte codigo:

In [ ]:
from itertools import product, islice

import random

# Variáveis fixas
var_fixas = ['idades', 'sexos', 'alturas', 'pesos', 'atividades_fisicas', 'consumos_de_agua_diarios', 'BMI']

# Variáveis não fixas
idades = [18, 20, 26, 30, 35, 40, 47, 55, 60, 65]
sexos = ['Feminino', 'Masculino']
alturas = [1.50, 1.60, 1.70, 1.80, 1.90, 2.00]
pesos = [60.5, 70.0, 80.0, 90.0, 100.0, 110.0]
atividades_fisicas = ['Moderada', 'Intensa', 'Leve']
consumos_de_agua_diarios = ['1L', '1.5L', '2L', '2.5L', '3L']

# Cria todas as combinações possíveis das variáveis não fixas
combinacoes = list(product(idades, sexos, alturas, pesos, atividades_fisicas, consumos_de_agua_diarios))

# Seleciona aleatoriamente as combinações sem repetição
num_samples = min(len(combinacoes), len(var_fixas) * 700)
combinacoes_aleatorias = random.sample(combinacoes, num_samples)

# Imprime as variáveis fixas
print(','.join(var_fixas))

# Imprime as combinações aleatórias
for combinacao in combinacoes_aleatorias:
    idade, sexo, altura, peso, atividade_fisica, consumo_de_agua_diario = combinacao
    imc = peso / (altura ** 2)
    if imc < 18.5:
        bmi = 'baixo'
    elif imc < 24.9:
        bmi = 'normal'
    else:
        bmi = 'alto'
    print(f'{idade},{sexo},{altura},{peso},{atividade_fisica},{consumo_de_agua_diario},{bmi}')


In [1]:
import csv
from google.colab import files

# Faça upload do arquivo txt
uploaded = files.upload()

# Abra o arquivo txt
for fn in uploaded.keys():
  with open(fn, 'r') as in_file:
      # Remova espaços em branco e divida cada linha em uma lista
      stripped = (line.strip() for line in in_file)
      lines = (line.split(",") for line in stripped if line)
      # Abra o arquivo csv e escreva as linhas
      with open('arquivo.csv', 'w') as out_file:
          writer = csv.writer(out_file)
          writer.writerows(lines)

# Faça download do arquivo csv
files.download('arquivo.csv')

Saving Quadra,Lote,Situação,Cliente,Projet.txt to Quadra,Lote,Situação,Cliente,Projet.txt


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [8]:
import math

# Tamanho da tabela hash
M = 13

# Constante A
A = 0.618

# Chaves para inserir na tabela hash
keys = [200, 10, 14, 24, 20, 13, 15, 96, 6, 35, 63, 12]

# Inicializa a tabela hash com M listas vazias
hash_table = [[] for _ in range(M)]

# Insere cada chave na tabela hash
for key in keys:
    # Calcula o valor hash da chave
    hash_value = math.floor(M * (key * A % 1))

    # Insere a chave na posição correspondente à sua hash
    hash_table[hash_value].append(key)

# Imprime a tabela hash
for i, bucket in enumerate(hash_table):
    print(f"Bucket {i}: {bucket}")

Bucket 0: [13]
Bucket 1: []
Bucket 2: [10]
Bucket 3: [15]
Bucket 4: [20, 96]
Bucket 5: [12]
Bucket 6: []
Bucket 7: [200]
Bucket 8: [14, 35]
Bucket 9: [6]
Bucket 10: [24]
Bucket 11: []
Bucket 12: [63]


# A partir disso foi gerado uma nova dataset com os seguintes atributos

Idades: Este atributo representa a idade de uma pessoa em anos. As opções disponíveis são 18, 20, 26, 30, 35, 40, 47, 55, 60, 65.

Sexos: Este atributo representa o sexo de uma pessoa. As opções disponíveis são ‘Feminino’ e ‘Masculino’.

Alturas: Este atributo representa a altura de uma pessoa em metros. As opções disponíveis são 1.50, 1.60, 1.70, 1.80, 1.90, 2.00.

Pesos: Este atributo representa o peso de uma pessoa em quilogramas. As opções disponíveis são 60.5, 70.0, 80.0, 90.0, 100.0, 110.0.

Atividades Físicas: Este atributo representa o nível de atividade física de uma pessoa. As opções disponíveis são ‘Moderada’, ‘Intensa’ e ‘Leve’.

Consumos de Água Diários: Este atributo representa a quantidade de água que uma pessoa consome diariamente. As opções disponíveis são ‘1L’, ‘1.5L’, ‘2L’, ‘2.5L’, ‘3L’.

BMI:O Índice de Massa Corporal (BMI, do inglês Body Mass Index) é uma medida usada para determinar se uma pessoa tem um peso saudável em relação à sua altura. É calculado dividindo o peso de uma pessoa (em quilogramas) pelo quadrado de sua altura (em metros).
A fórmula para calcular o BMI é:
BMI=altura2peso​
Por exemplo, se uma pessoa pesa 70 kg e tem 1,75 m de altura, o BMI seria calculado como:
BMI=1.75270​≈22.86

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
#Ler o dataset
ds = pd.read_csv("/content/drive/MyDrive/bmi_prediction_dataset.csv", sep=',', encoding='iso-8859-1')
#sep é o separador e encoding é a codificação dos caracteres, normalmente utiliza-se o iso-8859-1, utf-8, latin-1

Pré-processamento dos dados:

In [ ]:
ds2 = pd.DataFrame.copy(ds)

In [ ]:
#Visualizar os tipos dos dados e a quantidade de dados não nulos
ds2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4900 entries, 0 to 4899
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   idades                    4900 non-null   int64  
 1   sexos                     4900 non-null   object 
 2   alturas                   4900 non-null   float64
 3   pesos                     4900 non-null   float64
 4   atividades_fisicas        4900 non-null   object 
 5   consumos_de_agua_diarios  4900 non-null   object 
 6   BMI                       4900 non-null   object 
dtypes: float64(2), int64(1), object(4)
memory usage: 268.1+ KB


Tipos de atributos:

float64: float

int64: int

object: object

complex: complexos


In [ ]:
#Verificar a contagem de frequência de cada classe do atributo ChestPainType
ds2['BMI'].value_counts()

alto      3126
normal    1361
baixo      413
Name: BMI, dtype: int64

In [ ]:
from sklearn.utils import resample

#Balanceamento dos dados
classe_majoritaria = ds2[ds2['BMI'] == 'alto']
classe_normal = ds2[ds2['BMI'] == 'normal']
classe_minoritaria = ds2[ds2['BMI'] == 'baixo']

classe_majoritaria_subamostrada = resample(classe_majoritaria,
                                           replace=False,
                                           n_samples=3126,
                                           random_state=42)

ds2 = pd.concat([classe_majoritaria_subamostrada, classe_normal, classe_minoritaria])
ds2 = ds2.sample(frac=1, random_state=42).reset_index(drop=True)

Verificando a existência de valor nulos, ou faltantes (NAN):

In [ ]:
ds2.isnull().sum()

idades                      0
sexos                       0
alturas                     0
pesos                       0
atividades_fisicas          0
consumos_de_agua_diarios    0
BMI                         0
dtype: int64

Realizar a transformação de dados categóricos em numéricos manualmente.

In [ ]:
#replace - substitui os valores um DataFrame por outros valores de forma dinâmica.
ds2['sexos'].replace({'Masculino':0, 'Feminino': 1,}, inplace=True)
ds2['atividades_fisicas'].replace({'Leve':0, 'Moderada': 1, 'Intensa':2,}, inplace=True)
ds2['consumos_de_agua_diarios'].replace({'1L':0, '1.5L':1, '2L':2, '2.5L':3, '3L':4},inplace=True)
ds2['BMI'].replace({'baixo':0, 'normal':1, 'alto':2},inplace=True)

In [ ]:
ds2.head()

idades  sexos  alturas  pesos  atividades_fisicas  \
0      30      1      1.9   60.5                   2   
1      30      0      1.8   70.0                   2   
2      18      0      1.7  100.0                   0   
3      26      0      1.6   60.5                   0   
4      18      0      1.7   70.0                   1   

   consumos_de_agua_diarios  BMI  
0                         4    0  
1                         4    1  
2                         1    2  
3                         4    1  
4                         1    1

In [ ]:
ds2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4900 entries, 0 to 4899
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   idades                    4900 non-null   int64  
 1   sexos                     4900 non-null   int64  
 2   alturas                   4900 non-null   float64
 3   pesos                     4900 non-null   float64
 4   atividades_fisicas        4900 non-null   int64  
 5   consumos_de_agua_diarios  4900 non-null   int64  
 6   BMI                       4900 non-null   int64  
dtypes: float64(2), int64(5)
memory usage: 268.1 KB


In [ ]:
ds2.shape

(4900, 7)

In [ ]:
#previsores = conjunto de variáveis previsoras com as variáveis categóricas transformadas em numéricas manualmente (são os dados entrada).
previsores = ds2.iloc[:, 0:8].values
#iloc - df.iloc[<linhas>, <colunas>],
#neste exemplo, tem-se uma seleção de múltiplas linhas e colunas, no caso, todos os dados a partir da primeira coluna até a 11ª coluna,
#o retorno é um Pandas DataFrame.

In [ ]:
#Dados de entrada
previsores

array([[30. ,  1. ,  1.9, ...,  2. ,  4. ,  0. ],
       [30. ,  0. ,  1.8, ...,  2. ,  4. ,  1. ],
       [18. ,  0. ,  1.7, ...,  0. ,  1. ,  2. ],
       ...,
       [20. ,  0. ,  1.8, ...,  2. ,  1. ,  2. ],
       [26. ,  0. ,  1.8, ...,  1. ,  3. ,  1. ],
       [26. ,  1. ,  1.8, ...,  1. ,  2. ,  2. ]])

In [ ]:
previsores.shape

(4900, 7)

In [ ]:
#alvo = variável que se pretende atingir - tem ou não doença cardíaca (são os dados de saída)).
alvo = ds2.iloc[:, 6].values

In [ ]:
#Dados de saída
alvo

array([0, 1, 2, ..., 2, 1, 2])

Base de Treino e Teste O scikit-learn é uma biblioteca da linguagem Python para machine learning.

https://scikit-learn.org/stable/

In [ ]:
from sklearn.model_selection import train_test_split
#Usado para dividir os dados em subconjuntos aleatórios de treinamento e teste.

In [ ]:
x_treino, x_teste, y_treino, y_teste = train_test_split(previsores, alvo, test_size = 0.20, random_state = 0)
#test_size: tamanho em porcentagem dos dados de teste. default é none.
#random_state: controla o embaralhamento aplicado aos dados antes de aplicar a divisão.
#              É a nomeação de um estado aleatório (pata termos sempre o mesmo conjunto de treino e teste para poder comprar
#              qual é o melhor algoritmo, random_state = 0).

In [ ]:
pd.DataFrame(y_treino).value_counts()

2    2482
1    1101
0     337
dtype: int64

In [ ]:
pd.DataFrame(y_teste).value_counts()

2    644
1    260
0     76
dtype: int64

In [ ]:
#x_treino
x_treino.shape

(3920, 7)

In [ ]:
#x_teste
x_teste.shape

(980, 7)

In [ ]:
#y_treino
y_treino.shape

(3920,)

In [ ]:
#y_teste
y_teste.shape

(980,)

Importar as bibliotecas para métricas de avaliação e validação cruzada:

In [ ]:
# Para as métricas de avaliação dos modelos
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

accuracy_score: pontuação de classificação de precisão.

confusion_matrix: matriz de confusão para avaliar a precisão de uma classificação.

classification_report: apresenta um relatório das métricas da classificação. Apresenta as métricas precision, recall, F1-score para cada classe.

In [ ]:
#Para validação cruzada
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [ ]:
kfold = KFold(n_splits = 30, shuffle=True, random_state = 42)
#n_splis=5 (default)
#shuffle: se deve embaralhar os dados antes de dividir em lotes (as amostras dentro de cada divisão não serão embaralhadas)

Aprendizagem Baseada em Instâncias (KNN) https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html https://scikit-learn.org/stable/modules/generated/sklearn.metrics.DistanceMetric.html

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
# Criando o modelo
knn = KNeighborsClassifier(n_neighbors=7, metric ='minkowski', p=2) #p=1, usa a a manhatan, 2=euclediana

#Treinando o modelo
knn.fit(x_treino, y_treino)

KNeighborsClassifier(n_neighbors=7)

In [ ]:
previsoes_knn = knn.predict(x_teste)
previsoes_knn

array([2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 0, 2, 2, 2, 1, 1, 1, 2, 2, 2,
       2, 1, 2, 1, 2, 2, 2, 2, 2, 1, 0, 1, 2, 2, 1, 2, 1, 2, 1, 0, 1, 2,
       1, 2, 2, 0, 1, 2, 2, 0, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2,
       0, 2, 1, 2, 2, 1, 2, 0, 2, 1, 1, 1, 2, 1, 2, 1, 1, 2, 0, 1, 2, 2,
       1, 2, 2, 2, 0, 0, 2, 2, 1, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 0, 2, 0,
       0, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 2,
       2, 2, 0, 2, 1, 1, 1, 2, 2, 1, 1, 2, 1, 0, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 1, 2, 2, 1, 2, 0, 2, 2, 0, 1, 2, 2, 1, 2, 0, 1, 2, 2,
       1, 2, 1, 1, 2, 0, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2, 1, 2, 2, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 1, 2, 1, 1, 2, 2, 2, 2, 0, 1, 2, 2, 1, 2, 2, 0,
       2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2,
       2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       0, 2, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1, 1, 2, 2, 1, 2,
       2, 1, 2, 2, 1, 2, 2, 2, 0, 2, 1, 2, 2, 2, 2,

In [ ]:
y_teste

array([2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 0, 2, 2, 2, 1, 1, 1, 2, 2, 2,
       2, 1, 2, 1, 2, 2, 2, 2, 2, 1, 0, 1, 2, 2, 1, 2, 1, 2, 1, 0, 1, 2,
       1, 2, 2, 0, 1, 1, 2, 0, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2,
       0, 2, 1, 2, 2, 2, 2, 0, 2, 0, 2, 1, 2, 1, 2, 1, 1, 2, 0, 1, 2, 2,
       1, 2, 2, 2, 0, 0, 2, 2, 1, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 0, 2, 0,
       0, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 2,
       2, 2, 0, 2, 1, 1, 1, 2, 2, 1, 1, 2, 1, 0, 1, 1, 1, 1, 2, 2, 2, 1,
       2, 2, 2, 2, 2, 2, 2, 1, 2, 0, 2, 2, 0, 1, 2, 2, 1, 2, 0, 1, 1, 2,
       1, 2, 1, 1, 2, 0, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2, 1, 2, 2, 1, 2, 2,
       2, 1, 2, 2, 2, 2, 1, 2, 1, 1, 2, 2, 2, 2, 0, 2, 2, 2, 1, 2, 2, 0,
       2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2,
       2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,
       0, 2, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1, 1, 2, 2, 1, 2,
       2, 1, 2, 2, 1, 2, 2, 2, 0, 2, 1, 2, 1, 2, 2,

In [ ]:
print("Acurácia: %.2f%%" % (accuracy_score(y_teste, previsoes_knn) * 100.0))
print("Acurácia (quantidade amostras): %.2f" % (accuracy_score(y_teste, previsoes_knn, normalize=False) ))
#normalize: default=True. Se False, retorna o número de amostras classificadas corretamente

Acurácia: 94.69%
Acurácia (quantidade amostras): 928.00


In [ ]:
confusion_matrix(y_teste, previsoes_knn)

array([[ 62,  14,   0],
       [  1, 241,  18],
       [  0,  19, 625]])

In [ ]:
print(classification_report(y_teste, previsoes_knn, target_names=['Magresa', 'Normal', 'Obesidade'], digits=4))
#target_names: default=None. Nomes de exibição opcionais dos rótulos.
#digits:default=2. Número de dígitos para formatar os dados de saída.

              precision    recall  f1-score   support

     Magresa     0.9841    0.8158    0.8921        76
      Normal     0.8796    0.9269    0.9026       260
   Obesidade     0.9720    0.9705    0.9713       644

    accuracy                         0.9469       980
   macro avg     0.9452    0.9044    0.9220       980
weighted avg     0.9484    0.9469    0.9469       980



Validação Cruzada

In [ ]:
# Criando o modelo para validação cruzada
knnVC = KNeighborsClassifier(n_neighbors=7, metric='minkowski', p = 2)

resultado = cross_val_score(knnVC, previsores, alvo, cv = kfold)
#cv=None, validação cruzada padrão de 5 vezes

# Usando a média e o desvio padrão
print("Acurácia Média: %.2f%%" % (resultado.mean() * 100.0))

Acurácia Média: 95.96%


In [ ]:
resultado

array([0.93292683, 0.98170732, 0.93292683, 0.96341463, 0.96341463,
       0.95121951, 0.95121951, 0.97560976, 0.95731707, 0.97560976,
       0.99386503, 0.96932515, 0.94478528, 0.96319018, 0.96319018,
       0.95705521, 0.93251534, 0.97546012, 0.95705521, 0.98159509,
       0.94478528, 0.95092025, 0.97546012, 0.95705521, 0.93251534,
       0.95092025, 0.97546012, 0.94478528, 0.98159509, 0.95092025])

15 Neighbors

In [ ]:
# Criando o modelo
knn = KNeighborsClassifier(n_neighbors=15, metric ='minkowski', p=2) #p=1, usa a a manhatan, 2=euclediana

#Treinando o modelo
knn.fit(x_treino, y_treino)

KNeighborsClassifier(n_neighbors=15)

In [ ]:
previsoes_knn = knn.predict(x_teste)
previsoes_knn

array([2, 1, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 0, 2, 1, 2, 1, 1, 1, 2, 2, 2,
       2, 1, 2, 1, 2, 2, 2, 2, 2, 1, 0, 1, 2, 2, 1, 1, 1, 2, 1, 0, 1, 2,
       1, 2, 2, 1, 1, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2,
       0, 2, 2, 1, 2, 1, 2, 0, 2, 1, 1, 1, 2, 1, 2, 1, 1, 2, 1, 1, 2, 2,
       1, 2, 2, 2, 1, 1, 1, 2, 1, 2, 2, 2, 2, 2, 0, 1, 2, 2, 2, 1, 2, 1,
       1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 2,
       2, 2, 1, 2, 1, 1, 1, 2, 2, 1, 1, 2, 1, 0, 1, 1, 1, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 1, 2, 2, 1, 2, 0, 2, 2, 0, 1, 2, 2, 1, 2, 1, 1, 2, 2,
       1, 2, 1, 2, 2, 0, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2, 1, 2, 2, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 1, 1, 2, 2, 1, 2, 2, 0,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 1, 2, 2, 2, 2, 1, 1, 2,
       2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       0, 2, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1, 1, 2, 2, 1, 2,
       2, 1, 2, 2, 0, 2, 2, 2, 0, 2, 1, 2, 2, 2, 2,

In [ ]:
y_teste

array([2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 0, 2, 2, 2, 1, 1, 1, 2, 2, 2,
       2, 1, 2, 1, 2, 2, 2, 2, 2, 1, 0, 1, 2, 2, 1, 2, 1, 2, 1, 0, 1, 2,
       1, 2, 2, 0, 1, 1, 2, 0, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2,
       0, 2, 1, 2, 2, 2, 2, 0, 2, 0, 2, 1, 2, 1, 2, 1, 1, 2, 0, 1, 2, 2,
       1, 2, 2, 2, 0, 0, 2, 2, 1, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 0, 2, 0,
       0, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 2,
       2, 2, 0, 2, 1, 1, 1, 2, 2, 1, 1, 2, 1, 0, 1, 1, 1, 1, 2, 2, 2, 1,
       2, 2, 2, 2, 2, 2, 2, 1, 2, 0, 2, 2, 0, 1, 2, 2, 1, 2, 0, 1, 1, 2,
       1, 2, 1, 1, 2, 0, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2, 1, 2, 2, 1, 2, 2,
       2, 1, 2, 2, 2, 2, 1, 2, 1, 1, 2, 2, 2, 2, 0, 2, 2, 2, 1, 2, 2, 0,
       2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2,
       2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,
       0, 2, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1, 1, 2, 2, 1, 2,
       2, 1, 2, 2, 1, 2, 2, 2, 0, 2, 1, 2, 1, 2, 2,

In [ ]:
print("Acurácia: %.2f%%" % (accuracy_score(y_teste, previsoes_knn) * 100.0))
print("Acurácia (quantidade amostras): %.2f" % (accuracy_score(y_teste, previsoes_knn, normalize=False) ))
#normalize: default=True. Se False, retorna o número de amostras classificadas corretamente

Acurácia: 86.02%
Acurácia (quantidade amostras): 843.00


In [ ]:
confusion_matrix(y_teste, previsoes_knn)

array([[ 40,  36,   0],
       [  4, 214,  42],
       [  0,  55, 589]])

In [ ]:
print(classification_report(y_teste, previsoes_knn, target_names=['Magresa', 'Normal','Obesidade'], digits=4))
#target_names: default=None. Nomes de exibição opcionais dos rótulos.
#digits:default=2. Número de dígitos para formatar os dados de saída.

              precision    recall  f1-score   support

     Magresa     0.9091    0.5263    0.6667        76
      Normal     0.7016    0.8231    0.7575       260
   Obesidade     0.9334    0.9146    0.9239       644

    accuracy                         0.8602       980
   macro avg     0.8481    0.7547    0.7827       980
weighted avg     0.8701    0.8602    0.8598       980



Validação Cruzada

In [ ]:
# Criando o modelo para validação cruzada
from sklearn.naive_bayes import GaussianNB
naiveVC = GaussianNB()
resultado = cross_val_score(naiveVC, previsores, alvo, cv = kfold)
resultado

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# Usando a média e o desvio padrão
print("Acurácia Média: %.2f%%" % (resultado.mean() * 100.0))

Acurácia Média: 100.00%


In [ ]:
from sklearn.naive_bayes import BernoulliNB
#Criando o modelo
naive =  BernoulliNB()
#Treinando o modelo
naive.fit(x_treino, y_treino)


BernoulliNB()

In [ ]:
previsoes_naive = naive.predict(x_teste)
previsoes_naive

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2,
       2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       0, 2, 2, 2, 2, 2, 2, 0, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2,
       2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 0, 2, 0,
       0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2,
       2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 0,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2,

In [ ]:
y_teste

array([2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 0, 2, 2, 2, 1, 1, 1, 2, 2, 2,
       2, 1, 2, 1, 2, 2, 2, 2, 2, 1, 0, 1, 2, 2, 1, 2, 1, 2, 1, 0, 1, 2,
       1, 2, 2, 0, 1, 1, 2, 0, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2,
       0, 2, 1, 2, 2, 2, 2, 0, 2, 0, 2, 1, 2, 1, 2, 1, 1, 2, 0, 1, 2, 2,
       1, 2, 2, 2, 0, 0, 2, 2, 1, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 0, 2, 0,
       0, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 2,
       2, 2, 0, 2, 1, 1, 1, 2, 2, 1, 1, 2, 1, 0, 1, 1, 1, 1, 2, 2, 2, 1,
       2, 2, 2, 2, 2, 2, 2, 1, 2, 0, 2, 2, 0, 1, 2, 2, 1, 2, 0, 1, 1, 2,
       1, 2, 1, 1, 2, 0, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2, 1, 2, 2, 1, 2, 2,
       2, 1, 2, 2, 2, 2, 1, 2, 1, 1, 2, 2, 2, 2, 0, 2, 2, 2, 1, 2, 2, 0,
       2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2,
       2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,
       0, 2, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1, 1, 2, 2, 1, 2,
       2, 1, 2, 2, 1, 2, 2, 2, 0, 2, 1, 2, 1, 2, 2,

In [ ]:
print("Acurácia: %.2f%%" % (accuracy_score(y_teste, previsoes_naive) * 100.0))

Acurácia: 73.47%


In [ ]:
confusion_matrix(y_teste, previsoes_naive)

array([[ 76,   0,   0],
       [  0,   0, 260],
       [  0,   0, 644]])

In [ ]:
print(classification_report(y_teste, previsoes_naive, target_names=['Magresa', 'Normal', 'Obesidade'], digits=4))

              precision    recall  f1-score   support

     Magresa     1.0000    1.0000    1.0000        76
      Normal     0.0000    0.0000    0.0000       260
   Obesidade     0.7124    1.0000    0.8320       644

    accuracy                         0.7347       980
   macro avg     0.5708    0.6667    0.6107       980
weighted avg     0.5457    0.7347    0.6243       980



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Validação Cruzada

In [ ]:
# Criando o modelo para validação cruzada
naiveVC = BernoulliNB()
resultado = cross_val_score(naiveVC, previsores, alvo, cv = kfold)
resultado

array([0.67073171, 0.73780488, 0.75609756, 0.73780488, 0.65243902,
       0.70121951, 0.73780488, 0.7804878 , 0.74390244, 0.69512195,
       0.68711656, 0.73619632, 0.6809816 , 0.72392638, 0.7607362 ,
       0.68711656, 0.71165644, 0.74846626, 0.73006135, 0.71779141,
       0.72392638, 0.73006135, 0.7607362 , 0.77300613, 0.77300613,
       0.77300613, 0.66257669, 0.69325153, 0.6993865 , 0.6809816 ])

In [ ]:
# Usando a média e o desvio padrão
print("Acurácia Média: %.2f%%" % (resultado.mean() * 100.0))

Acurácia Média: 72.22%


ÁRVORE DE DECISÃO https://scikit-learn.org/stable/modules/tree.html

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [ ]:
arvore = RandomForestClassifier(n_estimators=5)

arvore.fit(x_treino, y_treino)

RandomForestClassifier(n_estimators=5)

In [ ]:
previsoes_arvore = arvore.predict(x_teste)

In [ ]:
print("Acurácia: %.2f%%" % (accuracy_score(y_teste, previsoes_arvore) * 100.0))


Acurácia: 100.00%


In [ ]:
confusion_matrix(y_teste, previsoes_arvore)

array([[ 76,   0,   0],
       [  0, 260,   0],
       [  0,   0, 644]])

In [ ]:
print(classification_report(y_teste, previsoes_arvore, target_names=['Magresa', 'Normal', 'Obesidade'], digits=4))

              precision    recall  f1-score   support

     Magresa     1.0000    1.0000    1.0000        76
      Normal     1.0000    1.0000    1.0000       260
   Obesidade     1.0000    1.0000    1.0000       644

    accuracy                         1.0000       980
   macro avg     1.0000    1.0000    1.0000       980
weighted avg     1.0000    1.0000    1.0000       980



Analisando os dados de treinamento

In [ ]:
previsoes_treino = arvore.predict(x_treino)

In [ ]:
print("Acurácia: %.2f%%" % (accuracy_score(y_treino, previsoes_treino)* 100.0))

Acurácia: 100.00%


In [ ]:
confusion_matrix(y_treino, previsoes_treino)

array([[ 337,    0,    0],
       [   0, 1101,    0],
       [   0,    0, 2482]])

A acurácia 100% indica que o modelo se ajustou muito bem com os dados de treinamento, mas com os dados de teste, o resultado é ruim. Quando isso ocorre é dito que o modelo aprendeu demais sobre os dados de treinamento, ele decorou. Isso é chamado de overfitting, ou sobreajuste. Uma forma de tentar resolver é configurar o hiperparâmetro max_depth, que é a profundidade máxima da árvore, significa fazer poda.

Validação Cruzada

In [ ]:
# Criando o modelo
modelo = RandomForestClassifier(n_estimators=5)

resultado = cross_val_score(modelo, previsores, alvo, cv = kfold)

# Usamos a média e o desvio padrão
print("Acurácia Média: %.2f%%" % (resultado.mean() * 100.0))

Acurácia Média: 100.00%


DecisionTreeClassifier

In [ ]:
arvore = DecisionTreeClassifier(criterion='entropy', max_depth=10, random_state = 0)
#arvore = DecisionTreeClassifier(criterion='gini', max_depth=10, random_state = 0)

#criterion: função para medir a qualidade da divisão, {“gini”, “entropia”, “log_loss”}, default=”gini”. Métricas como entropia, que é a medida da
#           falta de homogeneidade, e o índice de Gini, que é a medida do grau de heterogeneidade, são usdas para determinar o nível de importância
#           de um atributo (chamado de ganho de informação)
#max_depth=3: profundidade máxima da árvore (poda), se None, sem poda

arvore.fit(x_treino, y_treino)

DecisionTreeClassifier(criterion='entropy', max_depth=10, random_state=0)

In [ ]:
previsoes_arvore = arvore.predict(x_teste)

In [ ]:
print("Acurácia: %.2f%%" % (accuracy_score(y_teste, previsoes_arvore) * 100.0))

Acurácia: 100.00%


In [ ]:
confusion_matrix(y_teste, previsoes_arvore)

array([[ 76,   0,   0],
       [  0, 260,   0],
       [  0,   0, 644]])

In [ ]:
print(classification_report(y_teste, previsoes_arvore, target_names=['Magresa', 'Normal', 'Obesidade'], digits=4))

              precision    recall  f1-score   support

     Magresa     1.0000    1.0000    1.0000        76
      Normal     1.0000    1.0000    1.0000       260
   Obesidade     1.0000    1.0000    1.0000       644

    accuracy                         1.0000       980
   macro avg     1.0000    1.0000    1.0000       980
weighted avg     1.0000    1.0000    1.0000       980



Analisando os dados de treinamento

In [ ]:
previsoes_treino = arvore.predict(x_treino)

In [ ]:
print("Acurácia: %.2f%%" % (accuracy_score(y_treino, previsoes_treino)* 100.0))

Acurácia: 100.00%


In [ ]:
confusion_matrix(y_treino, previsoes_treino)

array([[ 337,    0,    0],
       [   0, 1101,    0],
       [   0,    0, 2482]])

A acurácia 100% indica que o modelo se ajustou muito bem com os dados de treinamento, mas com os dados de teste, o resultado é ruim. Quando isso ocorre é dito que o modelo aprendeu demais sobre os dados de treinamento, ele decorou. Isso é chamado de overfitting, ou sobreajuste. Uma forma de tentar resolver é configurar o hiperparâmetro max_depth, que é a profundidade máxima da árvore, significa fazer poda.

Validação Cruzada

In [ ]:
# Criando o modelo
modelo = DecisionTreeClassifier(criterion='entropy', max_depth=10, random_state = 0)
#modelo = DecisionTreeClassifier(criterion='gini', max_depth=10, random_state = 0)

resultado = cross_val_score(modelo, previsores, alvo, cv = kfold)

# Usamos a média e o desvio padrão
print("Acurácia Média: %.2f%%" % (resultado.mean() * 100.0))

Acurácia Média: 100.00%


SVM - MÁQUINAS DE VETORES DE SUPORTE https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html

In [ ]:
from sklearn.svm import SVC
#SVC = classificador de vetor de suporte

In [ ]:
svm = SVC(kernel='rbf', random_state=0, C = 40)

# hiperparâmetro kernel: transforma os dados. Default: rbf
# hiperparâmetro C: constante de penalização, controla a tolerância de erros. Quanto maior o valor de C, maior capacidade de separação das classes,
#                   porém, maior probabilidade de overfitting e tempo de treinamento. Default = 1.
svm.fit(x_treino, y_treino)

SVC(C=40, random_state=0)

In [ ]:
previsoes_svm = svm.predict(x_teste)

In [ ]:
print("Acurácia: %.2f%%" % (accuracy_score(y_teste, previsoes_svm) * 100.0))

Acurácia: 100.00%


In [ ]:
confusion_matrix(y_teste, previsoes_svm)

array([[ 76,   0,   0],
       [  0, 260,   0],
       [  0,   0, 644]])

In [ ]:
print(classification_report(y_teste, previsoes_svm, target_names=['Magresa', 'Normal', 'Obesidade'], digits=4))

              precision    recall  f1-score   support

     Magresa     1.0000    1.0000    1.0000        76
      Normal     1.0000    1.0000    1.0000       260
   Obesidade     1.0000    1.0000    1.0000       644

    accuracy                         1.0000       980
   macro avg     1.0000    1.0000    1.0000       980
weighted avg     1.0000    1.0000    1.0000       980



Analisando os dados de treinamento

In [ ]:
previsoes_treino = svm.predict(x_treino)

In [ ]:
print("Acurácia: %.2f%%" % (accuracy_score(y_treino, previsoes_treino)* 100.0))

Acurácia: 100.00%


In [ ]:
confusion_matrix(y_treino, previsoes_treino)

array([[ 337,    0,    0],
       [   0, 1101,    0],
       [   0,    0, 2482]])

Validação Cruzada

In [ ]:
# Criando o modelo
modelo = SVC(kernel='rbf', random_state=0, C = 40)

resultado = cross_val_score(modelo, previsores, alvo, cv = kfold)

# Usamos a média e o desvio padrão
print("Acurácia Média: %.2f%%" % (resultado.mean() * 100.0))

Acurácia Média: 100.00%
